### ISSUE TITLE
If an IPythonPackage doesn't declare template_directory or texinputs_directory, derive them?

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.plasTeX#33]
[Back in 2013](https://github.com/NextThought/nti.plasTeX/commit/26df94c9912e44248697e0800ba9cf49ed7c84be) a declarative method was added for finding template directories. Packages that don't provide that rely on configuring settings or the environment to find their templates.

Should we automatically add the directory containing the class implementing IPythonPackage to the template search path? 

Cons:
- It's implicit. "Explicit is better than implicit."
- It widens the search path, potentially unnecessarily, potentially slowing down search time.

Pros:
- It lets package authors be lazy 😄 

Anything else?

cc @papachoco

**Comment by jamadden** [comment]
I'm inclined to vote *no* on this one. There's already enough magic with plugins and the way packages are discovered in the first place. (Though you could argue that, ehh, what's a little more magic?)

**Comment by sajones** [comment]
Since this change will break existing packages, what burden is there in updating those packages to comply with new explicit behavior?

**Comment by jamadden** [comment]
This change doesn't (didn't) *remove* anything. It just added an explicit way to find template directories under the control of the package. If they were finding templates before, it must have been through some other mechanism (a setting).

**Comment by jamadden** [comment]
Our custom render code is still setting the environment variable XHTMLTEMPLATES, which is still respected. It appears to be setting it to the right place, although there's been a lot of refactoring in there so we are double-checking.

The environment variable is fairly explicit, although it is prone to breaking with refactoring....hence `template_directory` provided by a package.

**Comment by sajones** [comment]
From what I can tell the template stuff all breaks down with commit 1d4babad77b477d88704fd3face50d0cb7b2a6b1. The prior commit, d8f8f590848a2b29bf9fa0b11ce640d3979aeac6, finds all the templates with no issues.

**Comment by jamadden** [comment]
What about our code? We have to be on at least r95785 of nti.contentrendering to support plasTeX:

```
r95785 | jason.madden | 2016-08-30 11:18:56 -0500 (Tue, 30 Aug 2016) | 9 lines

nti.plasTeX has long had a configure.zcml, and it needs to be loaded.

We got away without doing so in the past because we duplicated what it
was doing, but we can't do that anymore. If we don't configure, we
don't get the template engines loaded and hence nothing actually
renders. One early symptom is that eclipse-toc.xml doesn't get
created.
```

**Comment by sajones** [comment]
@jamadden @papachoco The issue with our renderer was a conflict between the pinned version and the unpinned deps. I have updated the pinned versions and am going to attempt to pin all the currently unpinned deps to hopefully not recreate the situation where updating a supporting utility updates an unpinned dep that has a breaking change with the pinned portions of the code base.
